services:
  bd_mysql_proyecto:
    container_name: bd_mysql_proyecto
    image: mysql:9.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bd_base
      MYSQL_PASSWORD: userpassword
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql.sql:/docker-entrypoint-initdb.d/mysql.sql
  
  bd_phpmyadmin_proy:
    container_name: bd_phpmyadmin_proy
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - bd_mysql_proyecto
    ports:
      - "8889:80"
    environment:
      PMA_HOST: bd_mysql_proyecto
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
  
  bd_postgres_proy:
    container_name: bd_postgres_proy
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bd_compras_ventas_inventario
    ports:
      - "5541:5432"
    volumes:
      - postgres_data_db:/var/lib/postgresql/data
      - ./postgres.sql:/docker-entrypoint-initdb.d/postgres.sql
  
  pgadmin_proy:
    container_name: pgadmin_proy
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - bd_postgres_proy
    ports:
      - "9991:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin


  # cloudbeaver:
  #   image: dbeaver/cloudbeaver:latest
  #   container_name: cloudbeaver
  #   ports:
  #     - "8978:8978"
  #   restart: always

volumes:
  mysql_data:
  postgres_data_db: